---
apiVersion: "v1"
kind: "Service" 
spec: 
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 9779-tcp
      protocol: TCP
      port: 9779
      targetPort: 9779