---
- name: Login in OpenShift as administrator
  shell: "oc login --insecure-skip-tls-verify=true -u {{ admin_username }} -p {{ admin_password }} {{ openshift }}"
  when: "{{ deploy_jenkins }}"
  tags:
    - openshift
    - jenkins
    - admin

- name: Define project=openshift
  shell: "oc project openshift"
  when: "{{ deploy_jenkins }}"
  tags:
    - openshift
    - jenkins
    - admin

- name: Give Jenkins Service Account admin privileges
  shell: "oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:ci:jenkins -n ci"
  when: "{{ deploy_jenkins }}"
  tags:
    - openshift
    - jenkins
    - admin

- name: Create custom buildConfig for Jenkins
  shell: "oc create -f https://raw.githubusercontent.com/redhat-helloworld-msa/jenkins/master/custom-jenkins.build.yaml"
  when: "{{ deploy_jenkins }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins
    - admin

- name: Build a custom Jenkins instance
  shell: "oc start-build custom-jenkins-build --follow"
  when: "{{ deploy_jenkins }}"
  tags:
    - openshift
    - jenkins
    - build
    - admin

- name: Login in OpenShift as openshift-dev
  shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"
  tags:
    - openshift

- name: Create a new CI OpenShift project
  shell: "oc new-project ci"
  when: "{{ deploy_jenkins }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins

- name: Create an OpenShift pipeline in CI project
  shell: "oc create -f https://raw.githubusercontent.com/redhat-helloworld-msa/aloha/master/pipeline.yml"
  when: "{{ deploy_jenkins }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins