---
- name: Verify if variables are set
  fail:
    msg: "[Target directory] and/or [OpenShift host] is not defined. Please edit vars.yml"
  when: (workdir is undefined) or (openshift is undefined)

- name: Login in OpenShift as administrator
  shell: "oc login --insecure-skip-tls-verify=true -u {{ admin_username }} -p {{ admin_password }} {{ openshift }}"
  tags:
    - openshift
    - admin

- name: Adjust SCC
  shell: "oc patch scc restricted -p '{\"runAsUser\":{\"type\":\"RunAsAny\"}}'"
  when: adjust_scc

- name: Create Workdir
  file:
    path: "{{ workdir }}"
    state: directory

- name: Checkout source code from Github
  git:
    repo: "https://github.com/ochaloup/{{ item.name }}"
    dest: "{{ workdir }}/{{ item.name }}"
    update: yes
    version: "lra"
    refspec: "lra"
  with_items: "{{ msa_projects }}"
  when: "clone_modules"
  tags:
    - git

- name: Compile Java Projects
  shell: "mvn -f {{ workdir }}/{{ item.name }}/pom.xml package"
  with_items: "{{ msa_projects }}"
  when: "item.project == 'java'"
  tags:
    - compile

- name: NPM install NodeJS Projects
  shell: "npm --prefix {{ workdir }}/{{ item.name }} install {{ workdir }}/{{ item.name }}"
  with_items: "{{ msa_projects }}"
  when: "item.project == 'node'"
  tags:
    - compile
