// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## (Option 1) Install all microservices using Ansible

link:https://www.ansible.com/[Ansible] can be used to automate the bootstrap process to setup Helloworld-MSA in CDK. 

Make sure you have the following requirenments installed:

- Git
- Ansible 1.9+
- Maven 3.1+
- JDK 1.8
- NPM

And run the following commands:

----
$ git clone https://github.com/redhat-helloworld-msa/helloworld-msa
$ cd helloworld-msa/ansible
----

First, *edit the vars.yaml file* to define the *'workdir'* variable and set the absolute path where you want to "git checkout" the source code of the microservices.

Then execute:

----
$ ansible-playbook helloworld-msa.yml
----

The playbook will take approximately 20 minutes to complete. After that OpenShift should take more 10 minutes to finish the installation and boot of each microservice. The bootstrap process should complete within 30 minutes.

NOTE: This approach is used to make it easy to create an environment with all pieces of this demo. However in a real MSA environment, each microservice can *and should* be deployed independently. The following instructions allow you to understand the individual process to deploy each microservice.

