// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Use case: Configuring your application

link:https://github.com/redhat-helloworld-msa/hola[hola] microservice uses link:http://deltaspike.apache.org/documentation/configuration.html[DeltaSpike Configuration] to obtain the phrase that is displayed.

DeltaSpike allows the configuration to come from different *ConfigSources* (System properties, Environment variables, JNDI value, Properties file values). The microservices needs a configuration value called "hello" to display the provided value. If no value is informed, the default value (Hola de %s) is used.

We will use 2 different approaches to configure "hola" microservice:

- Environment variables
- link:https://docs.openshift.com/enterprise/3.2/dev_guide/configmaps.html[Openshift ConfigMaps]



### Environment variables

Update the DeploymentConfig:

----
$ oc env dc/hola hello="Hola de Env var"

# To unset the env var
$ oc env dc/hola hello-
----

### ConfigMaps

As you've seen, the definition of environment variables causes the DeploymentConfig to recreate the pods with that value set. OpenShift 3.2 allows the use of ConfigMaps

#### Create a ConfigMap from an existing file:

----
$ cd hola/
$ oc create configmap translation --from-file=translation.properties
$ oc get configmap translation -o yaml
----

#### Mount a volume from ConfigMap

Here we are creating a mounted volume in all pods that reads the file.

----
$ oc patch dc/hola -p '{"spec":{"template":{"spec":{"containers":[{"name":"hola","volumeMounts":[{"name":"config-volume","mountPath":"/etc/config"}]}],"volumes":[{"name":"config-volume","configMap":{"name":"translation"}}]}}}}'
----

#### Update the microservice to read the file

The POD needs a Java System Property to inform the location of the file.

----
$ oc env dc/hola JAVA_OPTIONS="-Dconf=/etc/config/translation.properties"
----

After the deployment, check that the config is present

----
$ oc get pods -l app=hola
$ oc rsh hola-?-????? 
sh-4.2$ cat /etc/config/translation.properties
sh-4.2$ exit
----

Update the ConfigMap and wait the POD to get updated.

----
$ oc edit configmap translation
----

NOTE: The synchronization between the ConfigMap and the mounted volume takes some time to be performed

