// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Create a project

In Openshift, click in the `"New Project"` button. Give it the name **"helloworld-msa"** 

IMPORTANT: You must use the exact project name since it will affect the generate endpoint's URLs

Or run:
----
$ oc login <Openshift IP>:8443 -u developer -p developer
$ oc new-project helloworld-msa
----

////

### Create all the services from a simple file. (No builder images)

WARNING: This doesn't install the builder images. Any change on the source, the pod should be built again using the instructions from each service.

NOTE: First you will need to fetch all pre-built docker images. The following commands will do that. It should take some minutes to complete since it will download aproximatelly 2.5 GB.

----
$ cd <PATH to CDK Vagrant file location>/
$ eval "$(vagrant service-manager env docker)"
$ docker pull docker.io/redhatmsa/aloha; docker pull docker.io/redhatmsa/api-gateway; docker pull docker.io/redhatmsa/bonjour; docker pull docker.io/redhatmsa/frontend; docker pull docker.io/redhatmsa/hello; docker pull docker.io/redhatmsa/hola; docker pull docker.io/redhatmsa/namaste; docker pull docker.io/redhatmsa/ola; docker pull docker.io/fabric8/hystrix-dashboard:1.0.15; docker pull docker.io/fabric8/turbine-server:1.0.15
----

Once that all images are available in the CDK internal registry, you can create the Openshift resources using *oc* command.

----
$ oc login 10.1.2.2:8443 -u openshift-dev -p devel
$ oc new-project helloworld-msa
$ oc create -f https://raw.githubusercontent.com/redhat-helloworld-msa/helloworld-msa/master/helloworld-msa.json
$ oc policy add-role-to-user admin system:serviceaccount:helloworld-msa:turbine
----

TIP: If any pods become "yellow"/"pending". Scale down it to 0 replicas and then scale it up again.

If you want to install each service individually, follow the instructions bellow.

////