// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Deploy the hello (JAX-RS/EAP) microservice

Choose one of the following options/approaches to deploy this microservice.

### Option 1: Deploy using Fabric8 plugin

Execute:

----
$ git clone https://github.com/redhat-helloworld-msa/hello
$ cd hello/
$ mvn clean package docker:build fabric8:json fabric8:apply -Popenshift
----

### Option 2: Deploy project via oc CLI

#### Basic project creation

----
$ git clone https://github.com/redhat-helloworld-msa/hello
$ cd hello/
$ oc new-build --binary --name=hello -l app=hello
$ mvn package -Popenshift; oc start-build hello --from-dir=. --follow
$ oc new-app hello -l app=hello,hystrix.enabled=true
$ oc expose service hello
----

#### (Optional) Enable Jolokia and Readiness probe

----
$ oc patch dc/hello -p '{"spec":{"template":{"spec":{"containers":[{"name":"hello","ports":[{"containerPort": 8778,"name":"jolokia"}]}]}}}}'
$ oc patch dc/hello -p '{"spec":{"template":{"spec":{"containers":[{"name":"hello","readinessProbe":{"httpGet":{"path":"/api/health","port":8080}}}]}}}}'
----

////

### Option 3: Deploy project using EAP 7.0 (Beta) builder template/imagestream

----
$ oc login 10.1.2.2:8443 (login with openshift-dev/devel credentials)
$ oc create -n helloworld-msa -f https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.3.0-1/jboss-image-streams.json
----

#### Option 3.1 -  Using oc CLI

Execute:

----
$ oc new-app --name hello jboss-eap70-openshift:1.3-Beta~https://github.com/redhat-helloworld-msa/hello -l app=hello,hystrix.enabled=true
$ oc expose service hello
$ oc logs -f bc/hello
----

#### Option 3.2 - Using Openshift console

- Select `jboss-eap70-openshift:1.3-Beta` xpaas builder image
- Name: `hello`
- Git URL: https://github.com/redhat-helloworld-msa/hello
- Click on `"Show advanced build and deployment options"`
- Add the label **hystrix.enabled** with the value **true**
- Click on `"Create"`. And them click on `"Continue to overview"`
- Wait for the build to complete. (You can click `"View log"` to follow the build logs)

////

### Test the service endpoint

Access: http://hello-helloworld-msa.rhel-cdk.10.1.2.2.xip.io/api/hello